### ISSUE TITLE
CommandExecuter.php - Question

### ISSUE THREAD

**Issue by Watch-Video** [sportarchive/CloudTranscode#30]
Hello ^_^

i have made a custom implementation but hangs on the execution routine.

following scenario: when i put the executer command into an foreach loop the executer gets only one time called.
$out = $this->executer->execute('some call', 1, array(2 => array("pipe", "w")), false, false, false, 1);

So what is wrong ?

Regards Sascha

**Comment by Watch-Video** [comment]
Solved it with adding -y to ffmpeg

**Comment by sportarc** [comment]
Great thanks for the feedback! Submit pull-requests if you fix bugs or do some improvements.
Happy new year
--nico
