### ISSUE TITLE
pollers/config needed?

### ISSUE THREAD

**Issue by koxon** [sportarchive/CloudTranscode#39]
I believe the pollers/config is not needed anymore is it ?

**Comment by TerrificMao** [comment]
I want to setup CloudTranscode on Amazon EC2, could you give more detail steps? I'm eager to learn this exciting project. Thanks.

**Comment by koxon** [comment]
Please, wait for the docker container to be ready and the documentation to
be updated.
It is not ready for deployment yet.

thanks

On Sun, Jun 28, 2015 at 9:49 PM, TerrificMao <notifications@github.com>
wrote:

> I want to setup CloudTranscode on Amazon EC2, could you give more detail
> steps? I'm eager to learn this exciting project. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sportarchive/CloudTranscode/issues/39#issuecomment-116372845>
> .
>



-- 
Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.
